### ISSUE TITLE
Tar ball should be 2.6 to correspond to license list version.

### ISSUE THREAD

**Issue by kestewart** [spdx/license-test-files#1]

**Comment by wking** [comment]
I don't think we want tarballs at all, because editing such opaque files does not produce useful diffs without extra tooling.  Instead, we can develop the corpus in unpacked directories, and point folks at different tagged releases of this repository if they're interested in a particular version.

**Comment by jmanbeck** [comment]
I did  a tarball because there are over 340 test files and x 2 because there is one set with license identifiers and one set without. This will only  grow, especially if we support other forms.  An archive seemed much easier to download and use and someone can run a local diff if they need to. All of these files are auto generated so they will never be individually edited unless something is broken and then we would have to think it through.

**Comment by wking** [comment]
On Wed, Sep 20, 2017 at 01:17:44PM -0700, jmanbeck wrote:
> I did  a tarball because there are over 340 test files…

linux.git has 60k files as of v4.13, and it's still not distributed as
a tar inside the Git repository.  Note that GitHub (and most Git
hosting platforms) provide a way to download a zip or tar archive of
any commit.  See the “Download ZIP” button under “Clone or download”,
which links to [1].

  $ curl -sLI https://github.com/spdx/license-test-files/archive/master.zip | grep -i '^http\|^content-type\|^location'
  HTTP/1.1 302 Found
  Content-Type: text/html; charset=utf-8
  Location: https://codeload.github.com/spdx/license-test-files/zip/master
  HTTP/1.1 200 OK
  Content-Type: application/zip

And the tar equivalent works too:

  $ curl -sLI https://github.com/spdx/license-test-files/archive/master.tar.gz | grep -i '^http\|^content-type\|^location'
  HTTP/1.1 302 Found
  Content-Type: text/html; charset=utf-8
  Location: https://codeload.github.com/spdx/license-test-files/tar.gz/master
  HTTP/1.1 200 OK
  Content-Type: application/x-gzip

These exports also work if you replace ‘master’ with a commit hash or
tag name:

  $ curl -sLI https://github.com/spdx/license-test-files/archive/6620841cde96e8a3ca0befbe991c8348b3265698.zip | grep -i '^http\|^content-type\|^location'
  HTTP/1.1 302 Found
  Content-Type: text/html; charset=utf-8
  Location: https://codeload.github.com/spdx/license-test-files/zip/6620841cde96e8a3ca0befbe991c8348b3265698
  HTTP/1.1 200 OK
  Content-Type: application/zip

> …because there is one set with license identifiers and one set
> without. This will only grow, especially if we support other forms.

Yeah.  The approach taken in #4 is going to lead to something like 5x
more files.  But I don't think 2k files in a structured directory tree
is going to be too many for a repository to handle, especially since
few of those are going to be changing from commit to commit as new
licenses are added.

> All of these files are auto generated so they will never be
> individually edited unless something is broken and then we would
> have to think it through.

With #3 and #4, I think we want to move towards manually generating
the content, although obviously canonical examples can continue to be
added automatically.  After we get over the initial hump (which I'm
happy to handle myself if the direction taken in #4 sounds promising),
I expect maintenance to be minimal, because we don't add new licenses
at a particularly rapid rate ;).

[1]: https://github.com/spdx/license-test-files/archive/master.zip

**Comment by goneall** [comment]
+1 on files rather than the tarball.  Makes it easier for tooling to access the files through the github API's and as mentioned by @wking , you can easily create a tarball from github.

**Comment by jmanbeck** [comment]
Im going to close this comment since we are talking about structure in a different thread and th elicense list version was added.
